# Generated by Django 6.0.4 on 2026-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('NL', 'NL')], max_length=2, unique=True)),
                ('image', models.ImageField(upload_to='menu/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
