# Generated by Django 6.0.4 on 2026-06-03 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_menucard'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucard',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
