# Generated by Django 6.0.4 on 2026-06-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_menucard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucard',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('NL', 'NL')], max_length=2),
        ),
    ]
