# Generated by Django 6.0.4 on 2026-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
