# Generated by Django 6.0.4 on 2026-06-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact_facebook_contact_instagram_contact_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
                ('signature_eng', models.CharField(max_length=255)),
                ('signature_nl', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=100)),
                ('title_nl', models.CharField(max_length=100)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
