# Generated by Django 6.0.4 on 2026-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_aboutus_foundersection_mission_value_whoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('description_eng', models.TextField()),
                ('description_nl', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='home/')),
            ],
        ),
    ]
