# Generated by Django 6.0.4 on 2026-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
