# Generated by Django 6.0.4 on 2026-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_ourstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(default='Why Choose Us', max_length=255)),
                ('title_nl', models.CharField(default='Why Choose Us', max_length=255)),
                ('icon', models.CharField(default='fa-star', max_length=100)),
                ('content_eng', models.TextField()),
                ('content_nl', models.TextField()),
            ],
        ),
    ]
