# Generated by Django 6.0.4 on 2026-06-16 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_reservation_special_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='open_hours',
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hours_en',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hours_nl',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
