# Generated by Django 6.0.4 on 2026-06-29 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='address_nl',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
